apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secrets
  namespace: tools # Must match the namespace SonarQube is in
type: Opaque
data:
  # This is 'YourSecretPassword' base64 encoded
  # Use `echo -n 'YourPassword' | base64` to get your own.
  POSTGRES_PASSWORD: "WW91clNlY3JldFBhc3N3b3Jk"
# sops:
#   (SOPS will add its metadata here after encryption)